services:
  db:
    image: postgres:16-alpine
    secrets:
      - db_user
      - db_passwd
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_passwd
      POSTGRES_DB: monitor
      TZ: Asia/Shanghai
      LANG: zh_CN.utf-8
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=zh-CN --encoding=UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

  backend:
    image: ghcr.io/saitewasreset/mission_backend_rs:latest
    secrets:
      - db_conn_url
      - redis_conn_url
      - access_token
    volumes:
      - backend_data:/instance
    environment:
      DATABASE_URL_FILE: /run/secrets/db_conn_url
      REDIS_URL_FILE: /run/secrets/redis_conn_url
      ACCESS_TOKEN_FILE: /run/secrets/access_token
      INSTANCE_DIR: /instance
    restart: unless-stopped

  frontend:
    image: ghcr.io/saitewasreset/drg_mission_monitor_webui:latest
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine-slim
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

secrets:
  db_user:
    file: ./secrets_user.txt
  db_passwd:
    file: ./secrets_passwd.txt
  db_conn_url:
    file: ./secrets_db_conn_url.txt
  redis_conn_url:
    file: ./secrets_redis_conn_url.txt
  access_token:
    file: ./secrets_access_token.txt

volumes:
  postgres_data:
  backend_data:
  redis_data:
