services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: xxx
      MYSQL_DATABASE: xxx
      MYSQL_USER: xxx
      MYSQL_PASSWORD: xxx
      TZ: Asia/Shanghai
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  backend:
    image: ghcr.io/saitewasreset/drg_mission_monitor_backend:0.11.0
    environment:
      DB_HOST: db
      DB_DATABASE: xxx
      DB_USER: xxx
      DB_PASSWORD: xxx
      ADMIN_PREFIX: xxx
    volumes:
      - backend_data:/app/instance
    restart: unless-stopped

  frontend:
    image: ghcr.io/saitewasreset/drg_mission_monitor_webui:0.9.0
    restart: unless-stopped

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  redis:
    image: redis
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mariadb_data:
  backend_data:
  redis_data:
